spring:
    profiles:
        active: dev
    datasource:
        driver-class-name: org.sqlite.JDBC
        url: jdbc:sqlite:database/library.db
        hikari:
            idle-timeout: 10000
            auto-commit: false
            minimum-idle: 1
            maximum-pool-size: 1
    jpa:
        # generate-ddl: true
        hibernate:
            # ddl-auto: create
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
                implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        show-sql: true
logging:
    level:
        org:
            springframework:
                # transaction: trace
    file:
        name: log/app.log
