// Generated by delombok at Sun Feb 19 21:29:28 ICT 2023
package hust.kien.project.model.author;

import hust.kien.project.model.LibraryLocatable;
import hust.kien.project.model.LibraryPersistable;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;

@Entity
public class Author implements LibraryLocatable, LibraryPersistable {
    @Id
    @GeneratedValue
    private Long id;
    private AuthorInfo authorInfo;

    public Author(AuthorInfo authorInfo) {
        this.authorInfo = authorInfo;
    }

    public Author(String name, int age) {
        this.authorInfo = AuthorInfo.builder().name(name).age(age).build();
    }


    @SuppressWarnings("all")
    public static class AuthorBuilder {
        @SuppressWarnings("all")
        private String name;
        @SuppressWarnings("all")
        private int age;

        @SuppressWarnings("all")
        AuthorBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @SuppressWarnings("all")
        public AuthorBuilder name(final String name) {
            this.name = name;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @SuppressWarnings("all")
        public AuthorBuilder age(final int age) {
            this.age = age;
            return this;
        }

        @SuppressWarnings("all")
        public Author build() {
            return new Author(this.name, this.age);
        }

        @Override
        @SuppressWarnings("all")
        public String toString() {
            return "Author.AuthorBuilder(name=" + this.name + ", age=" + this.age + ")";
        }
    }

    @SuppressWarnings("all")
    public static AuthorBuilder builder() {
        return new AuthorBuilder();
    }

    @SuppressWarnings("all")
    public Long getId() {
        return this.id;
    }

    @SuppressWarnings("all")
    public AuthorInfo getAuthorInfo() {
        return this.authorInfo;
    }

    @SuppressWarnings("all")
    public void setId(final Long id) {
        this.id = id;
    }

    @SuppressWarnings("all")
    public void setAuthorInfo(final AuthorInfo authorInfo) {
        this.authorInfo = authorInfo;
    }

    @Override
    @SuppressWarnings("all")
    public String toString() {
        return "Author(" + this.getId() + ", " + this.getAuthorInfo() + ")";
    }

    @SuppressWarnings("all")
    public Author() {
    }
}
